development:
  api_key: <%= Rails.application.credentials.cloudinary[:api_key] %>
  api_secret: <%  Rails.application.credentials.cloudinary[:api_secret] %>
  cloud_name: <%=  Rails.application.credentials.cloudinary[:cloud_name] %>
  enhance_image_tag: true
  static_file_support: false
  
production:
  api_key: <%= Rails.application.credentials.cloudinary[:api_key] %>
  api_secret: <%  Rails.application.credentials.cloudinary[:api_secret] %>
  cloud_name: <%=  Rails.application.credentials.cloudinary[:cloud_name] %>
  enhance_image_tag: true
  static_file_support: true
  
test:
  api_key: <%= Rails.application.credentials.cloudinary[:api_key] %>
  api_secret: <%  Rails.application.credentials.cloudinary[:api_secret] %>
  cloud_name: <%=  Rails.application.credentials.cloudinary[:cloud_name] %>
  enhance_image_tag: true
  static_file_support: false
